In [7]:
#question 1

import pandas as pd
binSize = pd.read_csv('E:/machine_test/BinSize.csv')
temperature = pd.read_csv('E:/machine_test/temperature.csv')
print(binSize)
print(temperature)

                ID  LATITUDE  LONGITUDE  ELEVATION STATE                 NAME  \
0      AE000041196    25.333     55.517       34.0   NaN  SHARJAH INTER. AIRP
1      AEM00041194    25.255     55.364       10.4   NaN           DUBAI INTL
2      AEM00041217    24.433     54.651       26.8   NaN       ABU DHABI INTL
3      AEM00041218    24.262     55.609      264.9   NaN          AL AIN INTL
4      AFM00040990    31.500     65.850     1010.0   NaN     KANDAHAR AIRPORT
...            ...       ...        ...        ...   ...                  ...
18254  ZA000067633   -15.250     23.150     1053.0   NaN                MONGU
18255  ZA000067743   -17.817     25.817      986.0   NaN          LIVINGSTONE
18256  ZI000067775   -17.917     31.133     1480.0   NaN     HARARE (KUTSAGA)
18257  ZI000067975   -20.067     30.867     1095.0   NaN             MASVINGO
18258  ZI000067983   -20.200     32.616     1132.0   NaN             CHIPINGE

      GSNFLAG HCNFLAG    WMOID             x             y  \
0         GSN     NaN  41196.0  5.579578e+06  2.816905e+06
1         NaN     NaN  41194.0  5.567782e+06  2.808232e+06
2         NaN     NaN  41217.0  5.532707e+06  2.716829e+06
3         NaN     NaN  41218.0  5.637301e+06  2.697815e+06
4         NaN     NaN  40990.0  6.243199e+06  3.502645e+06
...       ...     ...      ...           ...           ...
18254     GSN     NaN  67633.0  2.483523e+06 -1.695725e+06
18255     GSN     NaN  67743.0  2.733040e+06 -1.981163e+06
18256     GSN     NaN  67775.0  3.293948e+06 -1.992282e+06
18257     NaN     NaN  67975.0  3.223893e+06 -2.231352e+06
18258     GSN     NaN  67983.0  3.403669e+06 -2.246141e+06

                                        x_group  \
0        5497601.479782179 to 5594934.908498545
1        5497601.479782179 to 5594934.908498545
2        5497601.479782179 to 5594934.908498545
3         5594934.908498544 to 5692268.33721491
4        6178935.480796736 to 6276268.909513102
...                                         ...
18254   2480265.1895748563 to 2577598.618291222
18255   2674932.047007587 to 2772265.4757239525
18256   3258932.6193057783 to 3356266.048022144
18257   3161599.190589413 to 3258932.6193057788
18258  3356266.0480221435 to 3453599.4767385093

                                          y_group  \
0          2772265.475723952 to 2869598.904440318
1          2772265.475723952 to 2869598.904440318
2         2674932.047007587 to 2772265.4757239525
3         2674932.047007587 to 2772265.4757239525
4         3453599.476738509 to 3550932.9054548745
...                                           ...
18254  -1705072.2452288494 to -1607738.8165124834
18255   -1997072.531377945 to -1899739.1026615791
18256   -1997072.531377945 to -1899739.1026615791
18257    -2289072.817527041 to -2191739.388810675
18258    -2289072.817527041 to -2191739.388810675

                                                xy_group  \
0      5497601.479782179 to 5594934.908498545, 277226...
1      5497601.479782179 to 5594934.908498545, 277226...
2      5497601.479782179 to 5594934.908498545, 267493...
3      5594934.908498544 to 5692268.33721491, 2674932...
4      6178935.480796736 to 6276268.909513102, 345359...
...                                                  ...
18254  2480265.1895748563 to 2577598.618291222, -1705...
18255  2674932.047007587 to 2772265.4757239525, -1997...
18256  3258932.6193057783 to 3356266.048022144, -1997...
18257  3161599.190589413 to 3258932.6193057788, -2289...
18258  3356266.0480221435 to 3453599.4767385093, -228...

                                                    hash
0      1f6f0e89f4e937d934fe9acde2545e0d66bbcfe3b66320...
1      1f6f0e89f4e937d934fe9acde2545e0d66bbcfe3b66320...
2      35c9093084d26708afc5b482ea15ba52e3f20fb7cd781f...
3      2a6a7edad90579049fd1b3c3a990e8a8be90cb1975118e...
4      039e75bbef55baa3fecc0568dc3b245666a98b1bcba6b4...
...                                                  ...
18254  c1f39870d7200ac9fa7748c4d6688cbbe48cd3ac4c4a9e...
18255  25cba19cddf24c1999b6b8812cbccbb2fc8f3e64715d73...
18256  6c7f11051d64bc4f778b4d2417b11ec72b4f655aed5fea...
18257  1d695305fb4a37e8903ca1b196f14d940b84cbc1c31d4b...
18258  49aa45ff962c662a14fcbb47c83454c8714c4943993a15...

[18259 rows x 15 columns]
                 ID        Date Element  Data_Value
0       USW00094889  2014-11-12    TMAX          22
1       USC00208972  2009-04-29    TMIN          56
2       USC00200032  2008-05-26    TMAX         278
3       USC00205563  2005-11-11    TMAX         139
4       USC00200230  2014-02-27    TMAX        -106
...             ...         ...     ...         ...
165080  USC00205822  2015-06-09    TMAX         256
165081  USC00205822  2009-10-06    TMAX         167
165082  USC00205050  2014-07-14    TMAX         283
165083  USC00200230  2006-11-29    TMIN         117
165084  USC00207312  2006-09-04    TMIN         111

[165085 rows x 4 columns]

In [6]:
#question 2

import pandas as pd
weather = pd.read_csv('E:/machine_test/weather.csv')
print(weather)

    Year    Fires       Acres
0   2019   50 477   4 664 364
1   2018   58 083   8 767 492
2   2017   71 499  10 026 086
3   2016   67 743   5 509 995
4   2015   68 151  10 125 149
..   ...      ...         ...
89  1930  190 980  52 266 000
90  1929  134 895  46 230 000
91  1928  175 934  43 542 000
92  1927  158 438  38 531 000
93  1926   91 793  24 316 000

[94 rows x 3 columns]

In [ ]:
#question 3

#1

select pname,kname from person,kids,proj,dept,employ where pname="payment management" and dname="computer" and employ.pno=person.pno and kids.pno=employ.pno and dept.dno=person.dno

#2

select * from person,proj,works_on where works_on.prno=proj.prno and works_on.pno=person.pno

#3

select pname,pnosup,grade from person,employ where employ.pno=person.pno